version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 533267037285.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=533267037285.dkr.ecr.ap-south-1.amazonaws.com/webapp
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t webapp:latest -f dockerfile .
      - docker tag webapp:latest 533267037285.dkr.ecr.ap-south-1.amazonaws.com/webapp:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 533267037285.dkr.ecr.ap-south-1.amazonaws.com/webapp:latest
artifacts:
    files: 
      - imagedefinitions.json
      - appspec.yml

